/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FishingRouteImport } from './routes/fishing'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as CaveRouteImport } from './routes/cave'
import { Route as AnimalsRouteImport } from './routes/animals'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FishingRoute = FishingRouteImport.update({
  id: '/fishing',
  path: '/fishing',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const CaveRoute = CaveRouteImport.update({
  id: '/cave',
  path: '/cave',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsRoute = AnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/cave': typeof CaveRoute
  '/farm': typeof FarmRoute
  '/fishing': typeof FishingRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/cave': typeof CaveRoute
  '/farm': typeof FarmRoute
  '/fishing': typeof FishingRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/cave': typeof CaveRoute
  '/farm': typeof FarmRoute
  '/fishing': typeof FishingRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animals'
    | '/cave'
    | '/farm'
    | '/fishing'
    | '/friends'
    | '/inventory'
    | '/marketplace'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animals'
    | '/cave'
    | '/farm'
    | '/fishing'
    | '/friends'
    | '/inventory'
    | '/marketplace'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/animals'
    | '/cave'
    | '/farm'
    | '/fishing'
    | '/friends'
    | '/inventory'
    | '/marketplace'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalsRoute: typeof AnimalsRoute
  CaveRoute: typeof CaveRoute
  FarmRoute: typeof FarmRoute
  FishingRoute: typeof FishingRoute
  FriendsRoute: typeof FriendsRoute
  InventoryRoute: typeof InventoryRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fishing': {
      id: '/fishing'
      path: '/fishing'
      fullPath: '/fishing'
      preLoaderRoute: typeof FishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cave': {
      id: '/cave'
      path: '/cave'
      fullPath: '/cave'
      preLoaderRoute: typeof CaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals': {
      id: '/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalsRoute: AnimalsRoute,
  CaveRoute: CaveRoute,
  FarmRoute: FarmRoute,
  FishingRoute: FishingRoute,
  FriendsRoute: FriendsRoute,
  InventoryRoute: InventoryRoute,
  MarketplaceRoute: MarketplaceRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
